<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getGet('from_date');
$to_date = $this->request->getGet('to_date');
$stage = $this->request->getGet('stage');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-d');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

$stage_filter = $stage ? "AND stage_id = '$stage'" : '';

// ==============================
// GET SHOOTER LOG DATA
// ==============================
$log_data = $this->db->query("
    SELECT 
        transaction_id,
        transaction_date,
        checkin_time,
        checkout_time,
        shooter_name,
        shooter_type,
        stage_id,
        total_amount,
        status
    FROM tbl_transactions
    WHERE transaction_date BETWEEN '$from_date' AND '$to_date'
    AND status != 'CANCELLED'
    $stage_filter
    ORDER BY transaction_date DESC, checkin_time DESC
")->getResultArray();

// Landscape mode: 297mm width, 210mm height
$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();

// ==============================
// SET EQUAL MARGINS (20mm each side)
// ==============================
$left_margin = 20;
$right_margin = 20;
$pdf->SetLeftMargin($left_margin);
$pdf->SetRightMargin($right_margin);
$pdf->SetAutoPageBreak(true, 20);

// Available width = 297 - 20 - 20 = 257mm
$available_width = 257;

$pdf->SetTitle('Shooter Log');

// Header
$pdf->SetFont('Times', 'B', 18);
$pdf->Cell(0, 10, 'QCPD SHOOTING RANGE', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 14);
$pdf->Cell(0, 8, 'SHOOTER LOG', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 11);
$pdf->Cell(0, 6, $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
if($stage) {
    $pdf->Cell(0, 6, 'Stage: ' . $stage, 0, 1, 'C');
}
$pdf->Ln(8);

// ==============================
// TABLE HEADER - Column widths sum to 257mm
// ==============================
$pdf->SetFont('Times', 'B', 9);
$pdf->SetFillColor(220, 220, 220);

// Adjusted column widths for landscape (total = 257mm)
$col_id = 20;
$col_date = 28;
$col_time_in = 24;
$col_time_out = 24;
$col_shooter = 55;
$col_type = 24;
$col_stage = 24;
$col_amount = 32;
$col_status = 26;
// Total: 20+28+24+24+55+24+24+32+26 = 257mm ✓

$pdf->Cell($col_id, 7, 'ID', 1, 0, 'C', true);
$pdf->Cell($col_date, 7, 'DATE', 1, 0, 'C', true);
$pdf->Cell($col_time_in, 7, 'TIME IN', 1, 0, 'C', true);
$pdf->Cell($col_time_out, 7, 'TIME OUT', 1, 0, 'C', true);
$pdf->Cell($col_shooter, 7, 'SHOOTER', 1, 0, 'C', true);
$pdf->Cell($col_type, 7, 'TYPE', 1, 0, 'C', true);
$pdf->Cell($col_stage, 7, 'STAGE', 1, 0, 'C', true);
$pdf->Cell($col_amount, 7, 'AMOUNT', 1, 0, 'C', true);
$pdf->Cell($col_status, 7, 'STATUS', 1, 1, 'C', true);

// Table Body
$pdf->SetFont('Times', '', 8);
foreach($log_data as $row) {
    $pdf->Cell($col_id, 6, '#' . $row['transaction_id'], 1, 0, 'C');
    $pdf->Cell($col_date, 6, date('m/d/Y', strtotime($row['transaction_date'])), 1, 0, 'C');
    $pdf->Cell($col_time_in, 6, date('h:i A', strtotime($row['checkin_time'])), 1, 0, 'C');
    $pdf->Cell($col_time_out, 6, $row['checkout_time'] ? date('h:i A', strtotime($row['checkout_time'])) : '—', 1, 0, 'C');
    $pdf->Cell($col_shooter, 6, substr($row['shooter_name'], 0, 20), 1, 0, 'L');
    $pdf->Cell($col_type, 6, $row['shooter_type'], 1, 0, 'C');
    $pdf->Cell($col_stage, 6, 'Stage ' . $row['stage_id'], 1, 0, 'C');
    $pdf->Cell($col_amount, 6, 'P' . number_format($row['total_amount'], 2), 1, 0, 'R');
    $pdf->Cell($col_status, 6, $row['status'], 1, 1, 'C');
}

// ==============================
// FOOTER - PREVENT BLANK 2ND PAGE
// ==============================
// Get current Y position
$current_y = $pdf->GetY();

// Check if we need to add footer on current page or if it will create a new page
if($current_y > 180) {
    // If we're near the bottom, adjust footer position
    $pdf->SetY(-20);
} else {
    // Add small space before footer
    $pdf->Ln(5);
}

// Only add footer if we have content
if($pdf->PageNo() == 1) {
    $pdf->SetFont('Times', 'I', 8);
    $pdf->Cell(0, 5, 'Generated by: ' . $this->cuser . ' | ' . date('Y-m-d h:i A'), 0, 0, 'L');
    $pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of 1', 0, 1, 'R');
} else {
    // If there are multiple pages with actual content
    $pdf->SetFont('Times', 'I', 8);
    $pdf->Cell(0, 5, 'Generated by: ' . $this->cuser . ' | ' . date('Y-m-d h:i A'), 0, 0, 'L');
    $pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');
}

$pdf->Output();
exit;
?>