<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getGet('from_date');
$to_date = $this->request->getGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-d');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// ==============================
// GET STAGE USAGE DATA
// ==============================
$stage_data = $this->db->query("
    SELECT 
        stage_id,
        COUNT(*) as total_transactions,
        SUM(total_amount) as total_revenue,
        AVG(total_amount) as avg_revenue,
        SUM(CASE WHEN shooter_type = 'PNP' THEN 1 ELSE 0 END) as pnp_count,
        SUM(CASE WHEN shooter_type = 'CIVILIAN' THEN 1 ELSE 0 END) as civilian_count
    FROM tbl_transactions
    WHERE transaction_date BETWEEN '$from_date' AND '$to_date'
    AND status != 'CANCELLED'
    GROUP BY stage_id
    ORDER BY stage_id
")->getResultArray();

// Landscape mode: 297mm width, 210mm height
$pdf = new FPDF('L', 'mm', 'A4');
// REMOVED: $pdf->AliasNbPages();
$pdf->AddPage();

// ==============================
// SET EQUAL MARGINS (20mm each side)
// ==============================
$left_margin = 20;
$right_margin = 20;
$pdf->SetLeftMargin($left_margin);
$pdf->SetRightMargin($right_margin);
$pdf->SetAutoPageBreak(true, 20);

// Available width = 297 - 20 - 20 = 257mm
$available_width = 257;

$pdf->SetTitle('Stage Usage Report');

// Header
$pdf->SetFont('Times', 'B', 18);
$pdf->Cell(0, 10, 'QCPD SHOOTING RANGE', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 14);
$pdf->Cell(0, 8, 'STAGE USAGE REPORT', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 11);
$pdf->Cell(0, 6, $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// ==============================
// TABLE HEADER - Column widths sum to 257mm
// ==============================
$pdf->SetFont('Times', 'B', 10);
$pdf->SetFillColor(220, 220, 220);

// Column widths for landscape (total = 257mm)
$col_stage = 35;
$col_transactions = 40;
$col_revenue = 45;
$col_avg_revenue = 40;
$col_pnp = 30;
$col_civilian = 32;
$col_utilization = 35;
// Total: 35+40+45+40+30+32+35 = 257mm ✓

$pdf->Cell($col_stage, 8, 'STAGE', 1, 0, 'C', true);
$pdf->Cell($col_transactions, 8, 'TRANSACTIONS', 1, 0, 'C', true);
$pdf->Cell($col_revenue, 8, 'REVENUE', 1, 0, 'C', true);
$pdf->Cell($col_avg_revenue, 8, 'AVG REVENUE', 1, 0, 'C', true);
$pdf->Cell($col_pnp, 8, 'PNP', 1, 0, 'C', true);
$pdf->Cell($col_civilian, 8, 'CIVILIAN', 1, 0, 'C', true);
$pdf->Cell($col_utilization, 8, 'UTILIZATION', 1, 1, 'C', true);

// Table Body
$pdf->SetFont('Times', '', 9);
$total_trans = 0;
foreach($stage_data as $row) {
    $total_trans += $row['total_transactions'];
}

foreach($stage_data as $row) {
    $util = $total_trans > 0 ? ($row['total_transactions'] / $total_trans) * 100 : 0;
    $pdf->Cell($col_stage, 7, 'Stage ' . $row['stage_id'], 1, 0, 'C');
    $pdf->Cell($col_transactions, 7, number_format($row['total_transactions']), 1, 0, 'C');
    $pdf->Cell($col_revenue, 7, 'P' . number_format($row['total_revenue'], 2), 1, 0, 'R');
    $pdf->Cell($col_avg_revenue, 7, 'P' . number_format($row['avg_revenue'], 2), 1, 0, 'R');
    $pdf->Cell($col_pnp, 7, number_format($row['pnp_count']), 1, 0, 'C');
    $pdf->Cell($col_civilian, 7, number_format($row['civilian_count']), 1, 0, 'C');
    $pdf->Cell($col_utilization, 7, number_format($util, 1) . '%', 1, 1, 'C');
}

// ==============================
// FOOTER - PREVENT BLANK 2ND PAGE
// ==============================
// Get current Y position
$current_y = $pdf->GetY();

// Check if we need to add footer on current page or if it will create a new page
if($current_y > 180) {
    // If we're near the bottom, adjust footer position
    $pdf->SetY(-20);
} else {
    // Add small space before footer
    $pdf->Ln(5);
}

// Footer - using PageNo() directly instead of {nb}
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser . ' | ' . date('Y-m-d h:i A'), 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of 1', 0, 1, 'R');

$pdf->Output();
exit;
?>